demoText = "Jennifer Alaniz<br/>\
<br/>\
Professor Urista<br/>\
<br/>\
REL 200<br/>\
<br/>\
16 June 2014<br/>\
<br/>\
Islam and Rap Music: The Deeper Connection<br/>\
<br/>\
“Through Rap, Muslim youth were exposed to black history and non-Muslims were introduced to Islam” states Hisham Adi (Aidi 1). Rap has come a long way through the years and has become more than just a genre in music. When it comes to hip hop, specifically in rap, it is in a way a message that talks about “social, political and contradictions” as stated in the article, “Black and Blue: Remembering Islam and Hip Hop” by The Islamic Monthy (Black and Bluec: Remembering Islam and Hip Hop 1). Just as the quote states, rap has played a major role within the Islam religion and through rap, public opinions in connection with Islam beliefs have been rising up to today. The history of Islam being a major influence in hip hop had started with the Nation of Islam, which gives off the idea of ‘race war’. The Nation of Islam is the pathway that many artists in the rap world take to learn about Islam. In this organization, many rappers are participants, going to the events by the organization as well as donating money. Islam has become hip hops’ official religion, entering the lives of many rap artists, most of who were non-Muslims. The reasoning as to why Islam has been so effective is because of the messages that it gives off of social justice, self-knowledge and community (Black and Bluec: Remembering Islam and Hip Hop 1). These messages are what many rap artists feel most connection to and want everyone else in the world to know about. To this day, the Islam religion has played an impacting role within rap artists in the United States within the three following ways: having rap artists convert to the religion, using the Islam teachings in their lyrics, and influencing the youth to become more aware of the Islam religion.<br/>\
<br/>\
The conversion of the Islam religion had started all the way back to Malcom X, a man that many rap artists looked up to over the years. Malcom X was an activist of the Nation of Islam just as many rappers such as Ice Cube, Mos Def, Snoop Dogg, Loop, Eve and many more are. When it comes to the dedication of the Islam religion from the African American community, the most dedicated are Hip Hop and Rap singers. The way that many of the rap artists had learned of the Islam religion is through the Nation of Islam. The reasoning for this organization is “fighting and militant opposition to white racism and oppression of blacks” as mentioned in the article “Conversion to Islam among Rap and Hip Hop Artists, from Ice Cube to Snoop Dogg” (Conversion to Islam among Rap and Hip Hop Artists 1). For most rappers who have converted to becoming Muslims, they have strayed away from the violence that they once been involved with. One of these artists who have made a turn around and continues to change is Snoop Dogg. Snoop Dogg is known for his crimes and the usage of drugs. Now he is straightening up his life and trying to live a more conservative life. Snoop Dogg ended up converting his name to Snoop Lion because of his religious findings through Islam. Another artist who has changed his ways for the better is Loon, who had changed his name to an Islamic name, Amir Junaid (Conversion to Islam among Rap and Hip Hop Artists 1). Loon is a great example of a man who not only converted fully to Islam, but had showed the world within the music industry about Islam. Loon is a man is devoted to Allah, the known to be god in the Islam religion. Loon used to be a rap artists who worked in the Bad Boy Records Label Company and lived a life of “money and women” until he found his true calling into the Islamic world. Loon wanted to live a life that was of peace and eventually strayed away as a rapper to pursue his spiritually in a deeper sense (Furay 1). As stated in the article by The Islamic Monthly, “It is this pursuit for self-knowledge that has led many to convert to Islam, including hip hop artists” (Black and Bluec: Remembering Islam and Hip Hop 1). Rappers want to know of what is in them as individuals along with live a life beyond what is expected of the African Americans as being violent. To go beyond the conversion of rappers in the Islam world, there are even rappers such as Nas, who have not converted to a Muslim, but still use the some of the teachings in their music (Moussly 1). This shows that the religion does not have to be fully practiced but that the main ideas of it can still be preached.<br/>\
<br/>\
Beyond the conversion to the Islam religion along with changing their way of life, rappers have used the principle of Islam teachings to give meaning within their lyrics. The lyrics by the artists contain powerful messages in connection to Islam. In an article by Mona Moussly by the Al Arabiya News, “Despite dozens of American rappers embracing the religion, many of them often continue to use content that preaches a life of materialism”, which means the deliverance of the Islam message (Moussly 1). The music has gone beyond the common ideals of drugs, sex, and the gang life by these artists. It has become more on the teachings of the religion. It is common for many artists to have lyrics that are in regards to ‘Allah’, for that is the powerful figure they look up to. Sometimes when ‘Allah’ is being used by the rappers, it is more than a message to them but a prayer. The most common art of Islam is poetry, and many rap artists take what they learned from the poetry and transform it into rap music. The most powerful effect that they want this music to have to influence the listeners to become better people and strive for social justice (Moussly 1). There are an abundant amount of Islamic references in rap music. Some rappers such as Ice Cube, do not use a whole lot of references for the fact that he does not want to get attacked by listeners who may not approve of his message, but he uses enough to make his point. An example of the references used would be by Mos. Def, who is known to using Arabic words along with Islam principles in his music. Muslim rap artist work to let the people know of the problems that Muslims are facing. Furthermore, there had been mentions of how Muslims faced blame of the 9/11 tragedy and this is an example of what Muslim artists are trying to ratify. The lyrics that rappers create are a powerful tool. This tool is what lets people know what the ‘real’ Islam values are compared to what the rest of the world who are not Islamic, say about them (Islamic Influence in Hip Hop and Rap Music 1).<br/>\
<br/>\
In regards to rap artists who convert into a Muslim and use Islamic teachings in their music, has made an enormous impact on the youth today through their music. It is one thing to learn about Islam through a text book, however, it is another thing to hear and see people of the popular culture speaking on the religion. Music is one of the largest media of the nation today and is known to be very powerful when delivering messages. With rap, artists who believe solely in the ideals of Islamic have used rap as an effective form to reach out to the youth. Rappers want to the youth to become aware of the unity that Islam culture can bring and they also want to improve the generations to come in regards to racism. Many youths in the United States listen to the common music and sending a message dealing with Islam, attract the youth. This music reaches out to both non-Muslims and Muslims youths. For the Muslim youth, this kind of music teaches them to embrace their religion and their identity because most of them feel that are judge due to looking like foreigners (Aidi 1). By reaching out to the youth, the rappers are reaching out to a bigger community because it is the youth who will change the negative thoughts about Muslims. Beyond that, it is the youths who will lead other youths to better humanity. Also mentioned in The Islamic Monthly, is that “A second and third generation of young people who are growing up as Muslims in America and are profoundly impacted by hip-hop” are helping out the compromising of respect between the Muslims and Americans of the 21st century (Black and Bluec: Remembering Islam and Hip Hop 1). This kind of connection can bring more peace between the two cultures. Islam being taught to the youth is the attempt to unite all races which is what Islam is all about to these rappers. The usage of Islam hip hop has become so popular that sales of the music amount to about 1.8 million in just the United States. This has shown how impacted the younger generation is of the music due to the high selling of the rap artists music (Moussly 1).<br/>\
<br/>\
As it was shown, Islam among rap artists has become a big deal in the United States today. The African American culture has always experienced disconnect from other cultures. This disconnect mainly had to do with the in just treatment that they had experienced for years and so on. The Islamic religion helps make a passage way away from this disconnect and that this why rappers have turned to Islam. This is how both Islam and rapping goes hand in hand because both want peace in the world and move away from all the negativity that goes on. Rappers have learned about this religion through influential people before them as mentioned, Malcom X. Now rappers have converted, used their musical lyrics, and influenced the younger generations about the good teachings of Islam. This is the way that Islam has positively impacted popular culture in the United States. By living the teaching of Islam and talking the Islam way, younger audience can see more into the religion. As for the people who are already Muslim, they will learn more about the musical world along with how music can, such as rap, can be used as an influential tool to send out messages for the better.<br/>\
<br/>\
Works Cited<br/>\
<br/>\
Aidi, Hisham. “America’s Hip Hop Foreign Policy.” The Atlantic. 20 March 2014. Web. 16 June<br/>\
<br/>\
2014.<br/>\
<br/>\
“Black and Blue: Remembering Islam and Hip Hop.” The Islamic Monthly. 17 June 2012. Web.<br/>\
<br/>\
16 June 2014.\
<br/>\
“Coversion to Islam among Rap and Hip Hop Artists, from Ice Cube to Snoop Dogg.” Kodoom.<br/>\
<br/>\
9 Aug. 2009. Web. 16 June 2014.<br/>\
<br/>\
<br/>\
Furay, Steve. “Former Bad Boy Rapper Loon Discusses His Conversion to Islam.” Dynasty<br/>\
<br/>\
News. 15 July 2011. Web. 16 June 2014.<br/>\
<br/>\
“Islamic Influence in Hip Hop and Rap Music.” Make Your Own Beats. N.P. N.D. Web. 16 June<br/>\
<br/>\
2014.<br/>\
<br/>\
Moussly, Mona. “Hip Hop Don’t Stop as It Goes Islamic.” Al Arabiya News. 18 March 2009.<br/>\
<br/>\
Web. 16 June 2014.<br/>\
<br/>\
View as Page  Download<br/>";